export default {
  '(GMT+00:00) London': 'Europe/London',
  '(GMT-05:00) Eastern Time': 'America/New_York',
  '(GMT-06:00) Central Time': 'America/Chicago',
  '(GMT-07:00) Mountain Time': 'America/Denver',
  '(GMT-08:00) Pacific Time': 'America/Los_Angeles',
  '(GMT-09:00) Alaska Time': 'America/Anchorage',
  '(GMT-10:00) Hawaii Time': 'Pacific/Honolulu',
  '(GMT-04:00) Puerto Rico': 'America/Puerto_Rico',
  '(GMT-11:00) Pago Pago': 'Pacific/Pago_Pago',
  '(GMT-09:30) Marquesas': 'Pacific/Marquesas',
  '(GMT-04:30) Caracas': 'America/Caracas',
  '(GMT-03:30) Newfoundland Time - St. Johns': 'America/St_Johns',
  '(GMT-03:00) Araguaina': 'America/Araguaina',
  '(GMT-03:00) Buenos Aires': 'America/Argentina/Buenos_Aires',
  '(GMT-02:00) Sao Paulo': 'America/Sao_Paulo',
  '(GMT-01:00) Cape Verde': 'Atlantic/Cape_Verde',
  '(GMT+01:00) Paris': 'Europe/Paris',
  '(GMT+02:00) Cairo': 'Africa/Cairo',
  '(GMT+03:00) Moscow+00 - Moscow': 'Europe/Moscow',
  '(GMT+03:30) Tehran': 'Asia/Tehran',
  '(GMT+04:00) Dubai': 'Asia/Dubai',
  '(GMT+04:30) Kabul': 'Asia/Kabul',
  '(GMT+05:00) Karachi': 'Asia/Karachi',
  '(GMT+05:30) India Standard Time': 'Asia/Calcutta',
  '(GMT+05:45) Katmandu': 'Asia/Katmandu',
  '(GMT+06:00) Dhaka': 'Asia/Dhaka',
  '(GMT+06:30) Rangoon': 'Asia/Rangoon',
  '(GMT+07:00) Jakarta': 'Asia/Jakarta',
  '(GMT+08:00) China Time - Beijing': 'Asia/Shanghai',
  '(GMT+08:30) Pyongyang': 'Asia/Pyongyang',
  '(GMT+09:00) Tokyo': 'Asia/Tokyo',
  '(GMT+09:30) Central Time - Darwin': 'Australia/Darwin',
  '(GMT+10:00) Eastern Time - Brisbane': 'Australia/Brisbane',
  '(GMT+10:30) Central Time - Adelaide': 'Australia/Adelaide',
  '(GMT+11:00) Eastern Time - Melbourne, Sydney': 'Australia/Sydney',
  '(GMT+12:00) Nauru': 'Pacific/Nauru',
  '(GMT+13:00) Auckland': 'Pacific/Auckland',
  '(GMT+14:00) Apia': 'Pacific/Apia',
};
